name: EnchantmentAPI
version: '${project.version}'
main: com.github.clickinggames.enchantmentapi.EnchantmentAPI
api-version: 1.18
load: STARTUP
authors: [ 3rdactive ]
description: make custom enchantments!
commands:
  eapi:
    permission: 4
    description: EAPI
